version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=dart_test_backend
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=draz@123
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=dart_test_backend
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=draz@123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
