name: simple_crud_app
description: A simple CRUD application with Dart.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  # server
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.0

  # database
  postgres: ^2.6.3

  # dependecy injection
  get_it: ^7.6.0

  # authentication
  dart_jsonwebtoken: ^2.8.2

  # file handling
  mime: ^1.0.4
  path: ^1.8.0
  crypto: ^3.0.3

  # environment variables
  dotenv: ^4.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
