name: hello_world
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  # server
  shelf: ^1.4.2
  shelf_router: ^1.1.3

  # database
  postgres: ^2.6.2

  #dependecy injection
  get_it: ^8.0.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
